import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { NextPage, GetServerSideProps } from 'next'
import { GetCharacterResults, Character, Info } from 'types'
import imageLoader from 'imageLoader'
import Link from 'next/link'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

function PageList({ characters, currentPage, info }: { characters: Character[], currentPage: string, info: Info }) {
    const router = useRouter()
    return (
        <div className={styles.main}>
            <Head>
                <title>Sam Hutton</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='row'>
                {characters.map((character) => {
                    return <div className='col' key={character.id}>
                        <Link href={`/characters/${character.id}`}>
                            <h3>{character.name}</h3>

                        </Link>
                        <Image
                            loader={imageLoader}
                            unoptimized
                            src={character.image}
                            alt={character.name}
                            width="200"
                            height="200">

                        </Image>
                    </div>
                })}

            </div>

            <div>
                <button>
                    <Link href={`/pages/${handlePrevious(parseInt(currentPage), 1)}`}>
                        PREV

                    </Link>
                </button>
                <button>
                    <Link href={`/pages/${handleNext(parseInt(currentPage), info.pages)}`}>
                        NEXT
                    </Link>
                </button>
                <br/>
                <Link href={`/pages/${1}`}>
                    First page
                </Link>
            </div>
        </div>
    )
}

const handleNext = (currentPage: number, maxPage: number) => {
    let nextPage = currentPage + 1;

    if (nextPage < maxPage) {
        return nextPage;
    }
    else {
        return maxPage;
    }
}

const handlePrevious = (currentPage: number, minPage: number) => {
    let nextPage = currentPage - 1;

    if (nextPage > minPage) {
        return nextPage;
    }
    else {
        return minPage;
    }
}



export const getServerSideProps: GetServerSideProps = async (context) => {


    const res = await fetch(`https://rickandmortyapi.com/api/character/?page=${context.query.pageNum}`)

    const { results, info }: GetCharacterResults = await res.json();
    let pageNum = context.query.pageNum as string;

    return {
        props: {
            characters: results,
            currentPage: pageNum,
            info: info
        }
    }
}


export default PageList;